-- 2017-08-17
ALTER TABLE `holidays` ADD `name` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '假日名稱' AFTER `id`;
ALTER TABLE `holidays` ADD `created_at` TIMESTAMP on update CURRENT_TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增時間' AFTER `date`;
ALTER TABLE `holidays` ADD `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改時間' AFTER `created_at`;